version: '3.8'

services:
  shop-admin-db:
    image: mysql:8.0
    container_name: shop-admin-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ShopAdminDB
    ports:
      - '3307:3306'
    volumes:
      - shop-admin-db-data:/var/lib/mysql
    networks:
      - shop-admin-network

  shop-admin-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: shop-admin-phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: shop-admin-db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - shop-admin-db
    networks:
      - shop-admin-network

  shop-admin-minio:
    image: minio/minio:RELEASE.2025-04-08T15-41-24Z
    container_name: shop-admin-minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - shop-admin-minio-data:/data
    networks:
      - shop-admin-network

  shop-admin-minio-init:
    image: minio/mc
    restart: 'no'
    depends_on:
      - shop-admin-minio
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO...';
      until mc alias set minio http://shop-admin-minio:9000 admin admin123; do
        sleep 2;
      done;
      mc mb minio/shop-admin || true;
      mc anonymous set public minio/shop-admin;
      echo 'MinIO bucket created';
      "
    networks:
      - shop-admin-network

  shop-admin-redis:
    image: redis:7
    container_name: shop-admin-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - shop-admin-redis-data:/data
    networks:
      - shop-admin-network

  shop-admin-redis-insight:
    image: redis/redisinsight:latest
    container_name: shop-admin-redis-insight
    restart: always
    ports:
      - '5540:5540'
    environment:
      RI_REDIS_HOST: shop-admin-redis
      RI_REDIS_PORT: 6379
    depends_on:
      - shop-admin-redis
    networks:
      - shop-admin-network

volumes:
  shop-admin-db-data:
  shop-admin-minio-data:
  shop-admin-redis-data:

networks:
  shop-admin-network:
