version: '3.8'

services:
  app:
    image: antvrunss/shop-admin-api:latest
    container_name: shop-admin-api-prod
    restart: unless-stopped
    working_dir: /var/www
    env_file:
      - .env
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
      - redis
    networks:
      - shop-admin-api-network

  nginx:
    image: nginx:alpine
    container_name: shop-admin-nginx-prod
    restart: unless-stopped
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - shop-admin-api-network

  mysql:
    image: mysql:8.0
    container_name: shop-admin-mysql-prod
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: shop_admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: shop
      MYSQL_PASSWORD: shop
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - shop-admin-api-network

  redis:
    image: redis:alpine
    container_name: shop-admin-redis-prod
    restart: unless-stopped
    command: redis-server --requirepass redis123
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - shop-admin-api-network

  queue:
    image: antvrunss/shop-admin-api:latest
    container_name: shop-admin-queue-prod
    restart: unless-stopped
    working_dir: /var/www
    env_file:
      - .env
    volumes:
      - ./:/var/www
    command: php artisan queue:work --sleep=3 --tries=3 --timeout=90
    depends_on:
      - redis
      - mysql
    networks:
      - shop-admin-api-network

  scheduler:
    image: antvrunss/shop-admin-api:latest
    container_name: shop-admin-scheduler-prod
    restart: unless-stopped
    working_dir: /var/www
    env_file:
      - .env
    volumes:
      - ./:/var/www
    command: php artisan schedule:work
    depends_on:
      - app
    networks:
      - shop-admin-api-network

networks:
  shop-admin-api-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
